
- name: instalando pacotes - CentOS
  yum:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2', 'net-tools','htop']
    state: present
    update_cache: true

- name: disabilita SELinux - CentOS
  command: setenforce 0
- name: disabilita SELinux on reboot - CentOS
  selinux:
    state: disabled

- name: Alterando hostname para o padrao do arquivo hosts
  hostname:
    name="{{ inventory_hostname }}"
  when:
    ansible_fqdn != ansible_ssh_host
      
- name: Configurando /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{item}}"
    state: present
  when: hostvars[item]['ansible_facts']['default_ipv4'] is defined
  with_items:
    - "{{ groups['all'] }}"


- name: Disable firewall
  shell:
    systemctl stop firewalld && systemctl disable firewalld
  


