
- name: Alterando hostname para o padrao do arquivo hosts
  hostname:
    name="{{ inventory_hostname }}"
  when:
    ansible_fqdn != ansible_ssh_host
      
- name: Configurando /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{item}}"
    state: present
  when: hostvars[item]['ansible_facts']['default_ipv4'] is defined
  with_items:
    - "{{ groups['all'] }}"



- name: Get the host IP
  shell: host {{ ansible_fqdn }} | awk '{print $NF}' ; test ${PIPESTATUS[0]} -eq 0 
  register: host_sh
- debug: msg="{{ host_sh.stdout }}"


- name: Setup networking (interfaces)
  template: owner=root group=root mode=644
              src=ifcfg-interfaces
              dest=/etc/sysconfig/network-scripts/ifcfg-{{ item }}
  with_items: "{{ net_interfaces }}"
 
   
- name: Restart Network
  service: name=network state=restarted
