#!/bin/bash

msg=" Eh preciso informar 2 paremetros: <macaddress> <ipadress>"

[[ $# -ne 2 ]] && echo $msg && exit 1


sudo virsh net-update dados  add-last  ip-dhcp-host '<host mac="'$1'" ip="'$2'"/>' --live --config --parent-index 0



#add-host #2>erros_conversao.txt
if [ $? -eq 0 ]
then
  echo "host add com sucesso"
   sudo virsh net-dumpxml  dados | grep host\ mac
else
  echo "Houve uma falha ao add o host"
fi
