---
- name: create VMs
  hosts: kvm
  become: true

  vars_files:
    - vms.yml

  tasks:
    - name: get VM disks
      command: "ls {{ vm_location }}"
      register: disks
      changed_when: "disks.rc != 0"

    - name: create disk
      command: >
               virt-builder --format qcow2 centos-8.2
               -o /var/lib/libvirt/images/{{ item.key }}.{{ file_type }}
               --size 30G
               --hostname {{ item.key }}   
               --root-password password:{{ root_pass }} --selinux-relabel
               --firstboot-command 'useradd devops' 
               --firstboot-command 'echo 'password' | passwd --stdin devops'
              # --run /home/jcastro/Documents/estudos/kvm/install.sh
             #  --ssh-inject /home/jcastro/.ssh/id_rsa.pub


               



                          
      when: item.key not in disks.stdout
      with_dict: "{{ guests }}"

    - name: get list of VMs
      virt:
        command: "list_vms"
      register: vms

    - name: create vm
      command: >
                virt-install --import --name {{ item.key }}
                --memory {{ item.value.mem }} --vcpus {{ item.value.cpus }}
                --disk {{ vm_location }}/{{ item.key }}.{{ file_type }}
                --noautoconsole --os-variant {{ os_type }}  
                --network network={{ network }}
                --graphics vnc  
                    
      when: item.key not in vms.list_vms
      with_dict: "{{ guests }}"

    - name: start vm
      virt:
        name: "{{ item.key }}"
        state: running
      with_dict: "{{ guests }}"

