---
- name: create VMs
  hosts: kvm
  become: true
  vars_files:
    - vms.yml

  tasks:
    - name: get VM disks
      command: "ls {{ vm_location }}"
      register: disks
      changed_when: "disks.rc != 0"

    - name: create disk
      command: >
               virt-builder --format qcow2 centos-8.2
               -o {{ vm_location}}/{{ item.key }}.{{ item.value.file_type }}
               --size 30G
               --hostname {{ item.key }}   
               --root-password password:{{ root_pass }} --selinux-relabel
               --run /home/jcastro/Documents/estudos/kvm/install.sh
       
            
#     name: clone disk
#     command: >
#              virt-clone --original {{ item.key }}.{{ item.value.template}} --name 
       # --run /home/jcastro/Documents/estudos/kvm/install.sh
#                              



                          
      when: item.key not in disks.stdout
      with_dict: "{{ guests }}"

    - name: get list of VMs
      virt:
        command: "list_vms"
      register: vms

    - name: create vm
      command: >
                virt-install --import --name {{ item.key }}
                --memory {{ item.value.mem }} --vcpus {{ item.value.cpus }}
                --disk {{ vm_location }}/{{ item.key }}.{{ item.value.file_type }}
                --noautoconsole --os-variant {{ item.value.os_type }}   
                --graphics vnc  
                --network dados           
      when: item.key not in vms.list_vms
      with_dict: "{{ guests }}"

    - name: start vm
      virt:
        name: "{{ item.key }}"
        state: running
      with_dict: "{{ guests }}"
