VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


  $script = <<-SCRIPT

  
  yum install epel-release -y &&  yum install net-tools -y && yum install htop -y
 
  SCRIPT

 #yum install net-tools
 #yum install htop
# yum install open-vm-tools
# yum install bash-completion bash-completion-extras

config.vm.define "ansible" do |ansible| 
    ansible.vm.provider "virtualbox" do |v|
        v.customize [ "modifyvm", :id, "--cpus", "4" ]
        v.customize [ "modifyvm", :id, "--memory", "4096" ]
       
    ansible.vm.box = "centos/7"
    #ansible.vm.network "private_network", ip: "192.168.100.200"
    ansible.vm.hostname = "ansible"
    ansible.vm.provision "shell", inline: $script
        
        
        
end
end
end